version: "3"
services:
  blogson-mysql:
    container_name: "java-shop-mysql"
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: java-shop-mysql
      MYSQL_USER: java-shop-mysql
      MYSQL_PASSWORD: java-shop-mysql
    volumes:
      - ./config.cnf:/etc/mysql/conf.d/custom.cnf